"""WebTransport bindings for Python."""

from web_transport._crypto import certificate_hash, generate_self_signed
from web_transport._web_transport import (
    Client,
    ConnectError,
    SessionRejected,
    DatagramError,
    DatagramNotSupportedError,
    DatagramTooLargeError,
    ProtocolError,
    RecvStream,
    SendStream,
    Server,
    Session,
    SessionClosed,
    SessionClosedByPeer,
    SessionClosedLocally,
    SessionError,
    SessionRequest,
    SessionTimeout,
    StreamClosed,
    StreamClosedByPeer,
    StreamClosedLocally,
    StreamError,
    StreamIncompleteReadError,
    StreamTooLongError,
    WebTransportError,
)

__all__ = [
    "generate_self_signed",
    "certificate_hash",
    "WebTransportError",
    "SessionError",
    "ConnectError",
    "SessionRejected",
    "SessionClosed",
    "SessionClosedByPeer",
    "SessionClosedLocally",
    "SessionTimeout",
    "ProtocolError",
    "StreamError",
    "StreamClosed",
    "StreamClosedByPeer",
    "StreamClosedLocally",
    "StreamTooLongError",
    "StreamIncompleteReadError",
    "DatagramError",
    "DatagramTooLargeError",
    "DatagramNotSupportedError",
    "Server",
    "SessionRequest",
    "Client",
    "Session",
    "SendStream",
    "RecvStream",
]
